### PR TITLE
Update 5.problem.md

### PR DESCRIPTION
**Pull request by zhanglanqing**
修改 伯努利 分布，为 几何 分布。

### CODE REVIEW

**Comment by idf** [comment]
screen shot 2016-08-31 at 17 16 40
screen shot 2016-08-31 at 17 16 46

Which the file diff and diff preview is different? Unicode issue?

**Comment by zhanglanqing** [comment]
Oh, I didn't notice that.
Maybe just because CRLF and LF problem, I am not sure.
But I just checked the typesetting and the contents, they were not changed.

**Comment by zhanglanqing** [comment]
I think I have changed the "Bernoulli distribution" to the “Geometric distribution” , while  the other contents  or typesetting kept the original form.  But the "files changed" on github didn't show that correctly. I don't know why.  ( I am a "git beginner"  :(

**Comment by gzc** [comment]
I see. It's OK !

**Pull request merged**
